### PR TITLE
Basic navigation routes

### PR DESCRIPTION
**Pull request by Neathan**
### Changes
Added the basic navigation routes for the app.
I've included a demo page for the activity page that show how the stack navigation for each tab-page works.
I've also changed the slug name in the app.json to comply with the specification requirements.

### Issues
I would appreciate if someone else could test to build this branch and runt it on their own phone using the Expo Go app to see if the following issues (or others not mentioned) are present:

- Switching fast between tab-screens can sometimes cause the content/header to "flicker" (turn white for a split second).
- The bottom navigation can on some devices not detect a proper safe-area making it be obscured by the native UI elements.

### Feedback
If you are able to find a solution to any of the known issues please feel free to post a solution.

### CODE REVIEW

**Comment by EMattfolk** [comment]
I got it to work! Looks amazing!

I could not reproduce any of the issues on the web, which may or may not be good. But I did notice the button on the main page stopped working after clicking around a bit.

Also.. should the lock file be kept? I thought it was supposed to, but it might not matter. In that case we should add it to the .gitignore.

**Comment by Neathan** [comment]
> I could not reproduce any of the issues on the web, which may or may not be good. But I did notice the button on the main page stopped working after clicking around a bit.
> 
The issues i mentioned are only present on mobile devices AFAIK and i stuck to only testing it for mobile since i found the same issue with the navigation as you did. I think it has to do with that @react-navigation/native and the web build but im not 100% sure.

> Also.. should the lock file be kept? I thought it was supposed to, but it might not matter. In that case we should add it to the .gitignore.
> 
Yes. The lock file is intended to be kept in source control ([source](https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json)) but i'm not sure how this will be managed when merged.

**Comment by EMattfolk** [comment]
> Yes. The lock file is intended to be kept in source control ([source](https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json)) but i'm not sure how this will be managed when merged.

I think the format is optimized for merges/changes so it should not be a problem. We will hopefully not need to change it that often either unless we're updating some dependencies.

**Review by EMattfolk — APPROVED** [review]
Looks good!

I think we should have line endings UNIX-style. LF instead of CRLF. Most text editors have an option for that.

**Comment by malin-mallan** [comment]
I have tried it on my own phone (android) and it works! 
There is a deley tho when flipping page and the header and the text dissaper so every thing becomes black exept for the button in the bottom for a short moment.

**Comment by Neathan** [comment]
> I have tried it on my own phone (android) and it works!
>
Great!

> There is a deley tho when flipping page and the header and the text dissaper so every thing becomes **black** exept for the button in the bottom for a short moment.
>
The flickering is the issue i pointed out above, so it's good to know that it can be replicated on another device.

The darkness you describe is something im unaware of. Could you attach a screenshot of how it looks? Would be good to know what and why the styling differs.

**Comment by Neathan** [comment]
Also, are you using Android's built in Darktheme? @malin-mallan

**Comment by malin-mallan** [comment]
I have darktheme on my phone yes

https://user-images.githubusercontent.com/78034678/112849515-6f882c00-90a9-11eb-8862-4940ebc6a42f.mp4

**Comment by Neathan** [comment]
Thank you for the video!
Im starting to think that i might be an issue with the expo interactive app workflow. Since the information has to come from the local server before being rendered it takes some time before it has the information. For you it seems like it takes longer than what it does for me so the issues might actually be a non-issue if we're lucky. I will try to [build the app into a standalone application](https://docs.expo.io/distribution/building-standalone-apps/) and update here with the results here.

**Review by malin-mallan — COMMENTED** [review]
Looks good! 
Maybe you could write a comment that explains what a function do. 
Really good names on the variables, the code is easy to read!

**Review by malin-mallan — APPROVED** [review]
I ment to approve and not comment

**Pull request merged**
