### PR TITLE
Support for support persons in calendar

### PR DESCRIPTION
**Pull request by EMattfolk**
Title explains itself.

### CODE REVIEW

**Comment by EMattfolk** [comment]
Needs to be merged after #46

**Review by KaptenSkruvkork — APPROVED** [review]
all looks great!

**Review by LukasJonsson99 — APPROVED** [review]
Looks good overall. Only thing I thought about was that the "ok" and "cancel" buttons are now maybe a little too far down on the screen.

**Comment by EMattfolk** [comment]
> Looks good overall. Only thing I thought about was that the "ok" and "cancel" buttons are now maybe a little too far down on the screen.

Yeah, but it is not by *that* much. I will hopefully get something more consistent in #56

**Pull request merged**
